language: php

php:
  - 5.3
  - 5.4

before_install:
 - ./unit-tests/ci/install_prereqs.sh

before_script:
 - git submodule --quiet update --init --recursive
 - $(phpenv which php) compiler.php
 - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-test && make -j2 && sudo make install && phpenv config-add ../unit-tests/ci/test.ini)
 - ulimit -c unlimited || true

script:
 - $(phpenv which php) ./unit-tests/arithmetic.php
 - $(phpenv which php) ./unit-tests/flow.php

after_failure:
 - sudo apt-get -qq install gdb
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
